languageCode: de-ch
title: SOVBB
theme: sovbb-theme
params:
  logo: sovbb_logo.svg
  favicon: sovbb_favicon
  headercommentblock: |
    <!-- ######################################
    
         Content:         SOVBB
         Graphic Design:  https://waldluft.ch
         Implementation:  https://oetiker.ch
    
         ###################################### -->